SEPARATOR = '!'
HENDLER_ORDER = 'ORDER'
HENDLER_CATEGORY = 'CATEGORY'
HENDLER_PRODUCT = 'PRODUCT'
HENDLER_HISTORY_ORDER = 'HISTORY_ORDER'
HENDLER_ADD_COUNT_PRODUCT = 'HENDLER_ADD_COUNT_PRODUCT'
HENDLER_SUB_COUNT_PRODUCT = 'HENDLER_SUB_COUNT_PRODUCT'





